# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Physical execution plan for zephyr pipelines.

Physical operations are generated by the planner from logical operations.
They encapsulate execution logic as callables, decoupling the backend from
knowledge of logical operation types.
"""

from __future__ import annotations

import heapq
import logging
from collections.abc import Callable, Iterable, Iterator
from dataclasses import dataclass, field
from enum import StrEnum, auto
from itertools import groupby, islice
from typing import Any, Protocol

from rigging.filesystem import url_to_fs
from rigging.log_setup import configure_logging

from zephyr.dataset import (
    Dataset,
    FileEntry,
    FilterOp,
    FlatMapOp,
    GlobSource,
    GroupByOp,
    JoinOp,
    JoinType,
    LoadFileOp,
    MapOp,
    MapShardOp,
    ReduceOp,
    ReshardOp,
    SelectOp,
    ShardInfo,
    TakePerShardOp,
    WindowOp,
    WriteOp,
    resolve_glob,
)
from zephyr.expr import Expr, referenced_columns
from zephyr.readers import InputFileSpec, compute_parquet_splits, load_file, load_file_batch
from zephyr.shuffle import ScatterReader

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Shard protocol
# ---------------------------------------------------------------------------


class Shard(Protocol):
    """Protocol for a shard of data assigned to a single worker.

    Implementations:
    - ListShard: backed by iterable references (source data, non-scatter)
    - ScatterReader: backed by scatter zstd-chunk files with byte-range sidecar
    """

    def __iter__(self) -> Iterator: ...
    def get_iterators(self) -> Iterator[Iterator]: ...


@dataclass
class SourceItem:
    """A source item with its shard assignment.

    The `data` field contains either:
    - InputFileSpec for LoadFileOp pipelines (file loading with optional chunking)
    - Raw data (int, dict, str, etc.) for from_list/from_iterable pipelines
    """

    shard_idx: int
    data: Any


@dataclass
class Map:
    """Transform stream → stream via composed callable.

    Attributes:
        fn: Composed function that transforms an iterator to an iterator
        needs_shard_context: True if fn expects (stream, shard_info: ShardInfo).
    """

    fn: Callable[..., Iterator]
    needs_shard_context: bool = False


@dataclass
class Write:
    """Write stream to file, return path."""

    output_pattern: Callable[[int, int], str]  # (shard_idx, total_shards) → path
    writer_type: str  # For chunk aggregation: "jsonl", "parquet", "binary", "vortex"
    skip_existing: bool = False
    # Writer-specific parameters
    schema: Any = None  # For parquet


@dataclass
class Scatter:
    """Distribute items to output shards by key hash."""

    key_fn: Callable[[Any], Any]  # item → key
    num_output_shards: int
    sort_fn: Callable[[Any], Any] | None = None  # Optional secondary sort within each group
    combiner_fn: Callable | None = None  # Optional local pre-aggregation per key


@dataclass
class Reduce:
    """Merge sorted chunks and reduce per key."""

    key_fn: Callable[[Any], Any]
    reducer_fn: Callable[[Any, Iterator], Any]
    sort_fn: Callable[[Any], Any] | None = None  # Must match Scatter's sort_fn


@dataclass
class Fold:
    """Reduce stream to single value."""

    fn: Callable[[Iterator], Any]


@dataclass
class Reshard:
    """Redistribute chunks across shards."""

    num_shards: int


@dataclass
class Join:
    """Join two sorted streams."""

    fn: Callable[[Iterator, Iterator], Iterator]
    right_plan: PhysicalPlan | None = None


PhysicalOp = Map | Write | Scatter | Reduce | Fold | Reshard | Join


class StageType(StrEnum):
    """Type of stage execution."""

    MAP_WORKER = auto()
    REDUCE_WORKER = auto()
    RESHARD = auto()


def _map_gen(stream: Iterator, fn: Callable) -> Iterator:
    for item in stream:
        yield fn(item)


def _filter_gen(stream: Iterator, predicate: Callable) -> Iterator:
    for item in stream:
        if predicate(item):
            yield item


def _flatmap_gen(stream: Iterator, fn: Callable) -> Iterator:
    for item in stream:
        yield from fn(item)


def _reduce_gen(
    shard: ScatterReader,
    key_fn: Callable,
    reducer_fn: Callable,
    external_sort_dir: str,
) -> Iterator:
    merged = shard.merge_sorted_chunks(external_sort_dir)
    for key, grouped in groupby(merged, key=key_fn):
        result = reducer_fn(key, grouped)
        if isinstance(result, Iterator):
            yield from result
        else:
            yield result


def _select_gen(stream: Iterator, columns: tuple[str, ...]) -> Iterator:
    for item in stream:
        yield {k: item[k] for k in columns if k in item}


def _load_file_gen(stream: Iterator, loader: Callable, *, include_file_paths: bool, file_path_column: str) -> Iterator:
    for spec in stream:
        try:
            yield from loader(spec, include_file_paths=include_file_paths, file_path_column=file_path_column)
        except Exception as e:
            e.add_note(f"While loading from {spec}")
            raise


def compose_map(operations: list) -> Callable[[Iterator], Iterator]:
    """Compose logical map/filter/flatmap ops into a single stream transformer.

    Args:
        operations: List of fusible logical ops (MapOp, FilterOp, LoadFileOp, etc.)

    Returns:
        A function that transforms an iterator to an iterator.
        For MapShardOp, also passes shard_idx and total_shards as ShardInfo.
    """

    def pipeline(stream: Iterator, *, shard_idx: int = 0, total_shards: int = 1) -> Iterator:
        for op in operations:
            if isinstance(op, LoadFileOp):
                loader = load_file_batch if op.batch_mode else load_file
                stream = _load_file_gen(
                    stream,
                    loader,
                    include_file_paths=op.include_file_paths,
                    file_path_column=op.file_path_column,
                )
            elif isinstance(op, MapOp):
                stream = _map_gen(stream, op.fn)
            elif isinstance(op, FilterOp):
                stream = _filter_gen(stream, op.predicate)
            elif isinstance(op, FlatMapOp):
                stream = _flatmap_gen(stream, op.fn)
            elif isinstance(op, MapShardOp):
                stream = op.fn(stream, ShardInfo(shard_idx=shard_idx, total_shards=total_shards))
            elif isinstance(op, TakePerShardOp):
                stream = islice(stream, op.n)
            elif isinstance(op, WindowOp):
                stream = make_windows(stream, op.folder_fn, op.initial_state)
            elif isinstance(op, SelectOp):
                stream = _select_gen(stream, op.columns)
        return stream

    return pipeline


def compose_join(
    left_key_fn: Callable,
    right_key_fn: Callable,
    combiner_fn: Callable,
    join_type: JoinType,
) -> Callable[[Iterator, Iterator], Iterator]:
    """Create a join function.

    Args:
        left_key_fn: Function to extract key from left items
        right_key_fn: Function to extract key from right items
        combiner_fn: Function to combine matched items
        join_type: inner or left join semantics

    Returns:
        Function that takes (left_stream, right_stream) and yields joined items
    """

    def join_fn(left: Iterator, right: Iterator) -> Iterator:
        return _sorted_merge_join(left, right, left_key_fn, right_key_fn, combiner_fn, join_type)

    return join_fn


@dataclass
class PhysicalStage:
    """A stage in the plan (operations between shuffle boundaries).

    A stage contains a sequence of physical operations that can be executed
    together. The stage_type tells the backend HOW to execute it:
    - MAP_WORKER: Normal worker execution (map/filter/write)
    - REDUCE_WORKER: Memory-intensive worker execution (scatter/reduce/join)
    - RESHARD: Redistribute chunks across shards (no worker execution)
    """

    operations: list[PhysicalOp] = field(default_factory=list)
    stage_type: StageType = StageType.MAP_WORKER
    output_shards: int | None = None

    def stage_name(self, max_length: int | None = None) -> str:
        """Generate a descriptive name from operations.

        Args:
            max_length: Maximum length of the name (truncates with "..." if exceeded).
                        None means no limit. Must be >= 3 if specified.

        Returns:
            Name like "Map → Filter → Write" or "Map → Filter → ..." if truncated
        """
        assert max_length is None or max_length >= 3, "max_length must be at least 3"
        op_names = [type(op).__name__ for op in self.operations]
        name = " → ".join(op_names)
        if max_length is not None and len(name) > max_length:
            return name[: max_length - 3] + "..."
        return name


@dataclass
class PhysicalPlan:
    """Executable plan computed from a Dataset."""

    # inputs to the computation
    source_items: list[SourceItem]

    # list of stages to execute
    stages: list[PhysicalStage]

    @property
    def num_shards(self) -> int:
        """Total number of logical shards in the plan.

        This counts unique shard_idx values, not total SourceItems. When
        intra-shard parallelism is enabled, multiple SourceItems may belong
        to the same logical shard.
        """
        if not self.source_items:
            return 0
        return len({item.shard_idx for item in self.source_items})


@dataclass
class FusionState:
    """Incremental state for fusing logical operations into physical stages."""

    stages: list[PhysicalStage] = field(default_factory=list)
    current_ops: list[PhysicalOp] = field(default_factory=list)
    pending_fusible: list = field(default_factory=list)
    output_shards: int | None = None
    stage_type: StageType | None = None

    def _set_stage_type(self, op: PhysicalOp) -> None:
        if isinstance(op, (Reshard)):
            if self.stage_type is not None:
                raise ValueError("Reshard should be the only op in a RESHARD stage")
            self.stage_type = StageType.RESHARD
        elif isinstance(op, (Reduce, Join)):
            self.stage_type = StageType.REDUCE_WORKER
        else:
            if self.stage_type is None:
                # Map ops can happen after a Reduce, Fold, or Join, but in that case the physical
                # stage is treated like a reduce, since those require more memory.
                self.stage_type = StageType.MAP_WORKER

    def flush_pending(self) -> None:
        """Convert pending fusible ops to a physical Map."""
        if not self.pending_fusible:
            return

        needs_shard_context = any(isinstance(op, MapShardOp) for op in self.pending_fusible)
        op = Map(
            fn=compose_map(self.pending_fusible[:]),
            needs_shard_context=needs_shard_context,
        )
        self._set_stage_type(op)
        self.current_ops.append(op)
        self.pending_fusible = []

    def add_op(
        self,
        op: PhysicalOp,
        *,
        output_shards: int | None = None,
    ) -> None:
        """Add physical op to current stage.

        Flushes any pending fusible ops to a Map first, then adds this op.
        """
        self.flush_pending()
        self.current_ops.append(op)
        if output_shards is not None:
            self.output_shards = output_shards

        self._set_stage_type(op)

    def end_stage(self) -> None:
        """Flush pending ops and close current stage."""
        self.flush_pending()
        if self.current_ops:
            self.stages.append(
                PhysicalStage(
                    operations=self.current_ops[:],
                    stage_type=self.stage_type,
                    output_shards=self.output_shards,
                )
            )
            self.current_ops = []
            self.output_shards = None
            self.stage_type = None

    def finalize(self) -> list[PhysicalStage]:
        """Flush remaining ops and return completed stages."""
        self.end_stage()
        return self.stages


def _fuse_operations(operations: list) -> list[PhysicalStage]:
    """Fuse logical operations into physical stages.

    Transforms logical ops into physical ops:
    - Fusible ops (MapOp, FilterOp, LoadFileOp, etc.) → Map(fn=compose_map([...]))
    - WriteOp → Write(...)
    - GroupByOp → Scatter + [shuffle] + Reduce
    - ReduceOp → Fold + [reshard to 1] + Fold
    - ReshardOp → Reshard
    - JoinOp → Join (with pre-computed right_plan)

    Args:
        operations: List of logical operations

    Returns:
        List of PhysicalStages with physical operations and execution metadata
    """
    if not operations:
        return []

    state = FusionState()

    for op in operations:
        if isinstance(op, WriteOp):
            state.add_op(
                Write(
                    output_pattern=op.output_pattern,
                    writer_type=op.writer_type,
                    skip_existing=op.skip_existing,
                    schema=op.schema,
                )
            )

        elif isinstance(op, GroupByOp):
            num_shards = op.num_output_shards if op.num_output_shards is not None else -1
            state.add_op(
                Scatter(
                    key_fn=op.key_fn,
                    num_output_shards=num_shards,
                    sort_fn=op.sort_fn,
                    combiner_fn=op.combiner_fn,
                ),
                output_shards=num_shards if num_shards > 0 else None,
            )
            state.end_stage()
            state.add_op(Reduce(key_fn=op.key_fn, reducer_fn=op.reducer_fn, sort_fn=op.sort_fn))

        elif isinstance(op, ReduceOp):
            state.add_op(Fold(fn=op.local_reducer))
            state.end_stage()
            state.add_op(Reshard(num_shards=1), output_shards=1)
            state.end_stage()
            state.add_op(Fold(fn=op.global_reducer))

        elif isinstance(op, ReshardOp):
            state.end_stage()
            state.add_op(Reshard(num_shards=op.num_shards), output_shards=op.num_shards)
            state.end_stage()

        elif isinstance(op, JoinOp):
            right_plan = compute_plan(op.right_dataset)
            state.add_op(
                Join(
                    fn=compose_join(op.left_key_fn, op.right_key_fn, op.combiner_fn, op.join_type),
                    right_plan=right_plan,
                )
            )

        else:
            # Fusible ops: LoadFileOp, MapOp, FilterOp, FlatMapOp, MapShardOp, TakePerShardOp, WindowOp, SelectOp
            state.pending_fusible.append(op)

    return state.finalize()


def _compute_file_pushdown(
    files: list[FileEntry],
    load_op: LoadFileOp,
    operations: list,
) -> tuple[list[SourceItem], list]:
    """Create source items for file pipeline with pushdown optimizations applied.

    Args:
        files: List of FileEntry objects (path + size from bulk listing)
        load_op: The LoadFileOp specifying format and default columns
        operations: Full operations list (first op is LoadFileOp)

    Returns:
        Tuple of (source_items, remaining_operations), where filter/select have been pushed down.
    """
    filter_expr: Expr | None = None
    select_columns = load_op.columns
    ops_to_skip: set[int] = set()

    # We don't try to do anything fancy, e.g. AND multiple filters.
    # We can however aggregate select operations, though this is obviously unusual.

    for i, op in enumerate(operations):
        if isinstance(op, FilterOp) and op.expr is not None and filter_expr is None:
            if load_op.include_file_paths and load_op.file_path_column in referenced_columns(op.expr):
                # The filter references the injected file path column, which doesn't
                # exist in the source files. Stop pushdown so the filter runs normally
                # in the pipeline after the column has been injected.
                break
            filter_expr = op.expr
            ops_to_skip.add(i)
        elif isinstance(op, SelectOp) and select_columns is None:
            select_columns = list(op.columns)
            ops_to_skip.add(i)
        elif isinstance(op, FilterOp) and op.expr is None:
            # Lambda filter — can't introspect what columns it reads, so any
            # later SelectOp pushdown could KeyError the lambda by dropping
            # columns it needs. Stop pushdown here.
            break
        elif isinstance(op, (MapOp | FlatMapOp)):
            break  # Transform ops stop pushdown
        else:
            break

    # Create InputFileSpecs with final columns/filter.
    # When approx_shard_bytes is set, parquet files are split at row-group boundaries
    # into multiple SourceItems. Splits are best-effort: a row group is never divided,
    # so a shard can exceed approx_shard_bytes when a single row group is larger.
    source_items: list[SourceItem] = []
    for entry in files:
        path = entry.path
        is_parquet = load_op.format == "parquet" or (load_op.format == "auto" and path.endswith(".parquet"))
        if load_op.approx_shard_bytes is not None and is_parquet:
            for row_start, row_end in compute_parquet_splits(path, load_op.approx_shard_bytes):
                source_items.append(
                    SourceItem(
                        shard_idx=len(source_items),
                        data=InputFileSpec(
                            path=path,
                            format=load_op.format,
                            columns=select_columns,
                            row_start=row_start,
                            row_end=row_end,
                            filter_expr=filter_expr,
                        ),
                    )
                )
        else:
            source_items.append(
                SourceItem(
                    shard_idx=len(source_items),
                    data=InputFileSpec(
                        path=path,
                        format=load_op.format,
                        columns=select_columns,
                        filter_expr=filter_expr,
                    ),
                )
            )

    # Build final operations list: LoadFileOp + remaining ops
    final_ops = [load_op] + [op for i, op in enumerate(operations) if i not in ops_to_skip]

    return source_items, final_ops


def compute_plan(dataset: Dataset) -> PhysicalPlan:
    """Compute physical execution plan from logical dataset."""
    operations = list(dataset.operations)
    source = dataset.source

    # Resolve lazy glob sources into concrete FileEntry objects (with sizes).
    if isinstance(source, GlobSource):
        file_entries = resolve_glob(source)
        if operations and isinstance(operations[0], LoadFileOp):
            source_items, operations = _compute_file_pushdown(
                file_entries,
                operations[0],
                operations[1:],
            )
        else:
            # from_files() without load_file() — source items are plain paths
            source_items = [SourceItem(shard_idx=i, data=entry.path) for i, entry in enumerate(file_entries)]
    elif operations and isinstance(operations[0], LoadFileOp):
        # Non-glob source (e.g. from_list of paths) — wrap as FileEntry without sizes
        entries = [FileEntry(spec=InputFileSpec(path=p), size=0) for p in source]
        source_items, operations = _compute_file_pushdown(
            entries,
            operations[0],
            operations[1:],
        )
    else:
        source_list = list(source)
        source_items = [SourceItem(shard_idx=i, data=item) for i, item in enumerate(source_list)]

    stages = _fuse_operations(operations)
    return PhysicalPlan(source_items=source_items, stages=stages)


def make_windows(
    items: Iterable,
    folder_fn: Callable[[object, Any], tuple[bool, object]],
    initial_state: object,
) -> Iterator[list]:
    """Window items using a folder function.

    Args:
        items: Items to window
        folder_fn: Function (state, item) -> (should_continue, new_state)
        initial_state: Initial state for the folder function

    Yields:
        Windows of items (window closes when folder returns False)
    """
    window: list = []
    state = initial_state

    for item in items:
        should_continue, new_state = folder_fn(state, item)

        if not should_continue and window:
            # Close current window and start new one with this item
            yield window
            window = [item]
            state = initial_state
            # Re-apply folder with the item in the new window
            _, state = folder_fn(state, item)
        else:
            # Add item to current window
            window.append(item)
            state = new_state

    if window:
        yield window


def _sorted_merge_join(
    left_stream: Iterable,
    right_stream: Iterable,
    left_key_fn: Callable,
    right_key_fn: Callable,
    combiner_fn: Callable,
    join_type: JoinType,
) -> Iterator:
    """Perform a sorted merge join between two streams.

    Args:
        left_stream: Iterator of items from left side
        right_stream: Iterator of items from right side
        left_key_fn: Function to extract key from left items
        right_key_fn: Function to extract key from right items
        combiner_fn: Function to combine matched items
        join_type: inner or left join semantics

    Yields:
        Joined items according to join_type
    """
    # Tag both streams with their side for the merged iteration
    left_tagged = (("left", left_key_fn(item), item) for item in left_stream)
    right_tagged = (("right", right_key_fn(item), item) for item in right_stream)

    # Merge both sorted streams by key
    merged = heapq.merge(left_tagged, right_tagged, key=lambda x: x[1])

    # Group by key and apply join logic
    for _key, group in groupby(merged, key=lambda x: x[1]):
        left_group: list[Any] = []
        right_group: list[Any] = []
        for side, _, item in group:
            (left_group if side == "left" else right_group).append(item)

        if join_type == JoinType.INNER:
            if left_group and right_group:
                for left_item in left_group:
                    for right_item in right_group:
                        yield combiner_fn(left_item, right_item)
        elif join_type == JoinType.LEFT:
            for left_item in left_group:
                if right_group:
                    for right_item in right_group:
                        yield combiner_fn(left_item, right_item)
                else:
                    yield combiner_fn(left_item, None)


@dataclass
class StageContext:
    """Context for executing a stage on a shard.

    Encapsulates all the metadata and auxiliary data needed to process a shard.

    Attributes:
        shard: The shard data to process
        shard_idx: Index of this shard
        total_shards: Total number of shards
        aux_shards: Auxiliary shards for joins, keyed by op index
    """

    shard: Iterable[Any]
    shard_idx: int
    total_shards: int
    aux_shards: dict[int, Iterable[Any]] = field(default_factory=dict)

    def get_right_shard(self, op_index: int) -> Iterable[Any]:
        """Get right shard for join at given op index.

        Raises:
            ValueError: If no right shard is provided for the join
        """
        shard = self.aux_shards.get(op_index)
        if shard is None:
            raise ValueError(f"Expected exactly 1 right shard for join at op index {op_index}, got 0")
        return shard


def run_stage(
    ctx: StageContext,
    ops: list[PhysicalOp],
    external_sort_dir: str | None = None,
) -> Iterator:
    """Execute a stage's physical ops in a single pass, yielding plain items.

    This is the single worker function that backends call to execute physical ops.
    It only knows about physical op types (Map, Write, etc.) - not logical ops.

    All chunking, batching, and scatter routing is handled by the IO layer
    (the caller). For scatter stages, this yields the pre-scatter item stream;
    the caller extracts the Scatter op and passes its params to the writer.

    Args:
        ctx: Stage execution context providing shard data and metadata
        ops: List of physical operations to execute in sequence

    Yields:
        Pipeline items. The caller handles IO batching and scatter routing.
    """

    configure_logging(level=logging.INFO)

    from zephyr import counters  # circular import: counters → execution → plan
    from zephyr.writers import (  # circular import: writers → counters → execution → plan
        write_binary_file,
        write_jsonl_file,
        write_parquet_file,
        write_vortex_file,
    )

    stream: Iterator = iter(ctx.shard)

    op_index = 0
    while op_index < len(ops):
        op = ops[op_index]

        if isinstance(op, Map):
            if op.needs_shard_context:
                stream = op.fn(stream, shard_idx=ctx.shard_idx, total_shards=ctx.total_shards)
            else:
                stream = op.fn(stream)
            op_index += 1
        elif isinstance(op, Write):
            output_path = op.output_pattern(ctx.shard_idx, ctx.total_shards)

            if op.skip_existing:
                fs = url_to_fs(output_path)[0]
                if fs.exists(output_path):
                    logger.info(f"Skipping write, output exists: {output_path}")
                    counters.increment("zephyr/partitions_skipped")
                    yield output_path
                    return

            if op.writer_type == "jsonl":
                write_jsonl_file(stream, output_path)
            elif op.writer_type == "parquet":
                write_parquet_file(stream, output_path, schema=op.schema)
            elif op.writer_type == "binary":
                write_binary_file(stream, output_path)
            elif op.writer_type == "vortex":
                write_vortex_file(stream, output_path, schema=op.schema)
            else:
                raise ValueError(f"Unknown writer_type: {op.writer_type}")

            yield output_path
            return

        elif isinstance(op, Scatter):
            # Scatter routing is handled by the IO writer, not run_stage.
            # Yield the pre-scatter item stream; the caller extracts the
            # Scatter op and passes its params to the writer.
            yield from stream
            return

        elif isinstance(op, Reduce):
            # Build ScatterReader directly from per-mapper sidecars, then
            # merge sorted chunks and reduce per key.
            shard = ctx.shard
            if not isinstance(shard, ScatterReader):
                # Shard contains every mapper's scatter-data path — reducer
                # reads all sidecars in parallel and filters for its target.
                scatter_paths = list(shard)
                shard = ScatterReader.from_sidecars(scatter_paths, ctx.shard_idx)
            stream = _reduce_gen(shard, op.key_fn, op.reducer_fn, external_sort_dir)
            op_index += 1

        elif isinstance(op, Fold):
            # Reduction to single value
            result = op.fn(stream)
            stream = iter([result])
            op_index += 1

        elif isinstance(op, Reshard):
            # Reshard is handled by the backend, not in worker
            raise ValueError("Reshard should not be executed in run_stage")

        elif isinstance(op, Join):
            right_shard = ctx.get_right_shard(op_index)
            stream = op.fn(stream, iter(right_shard))
            op_index += 1

    # Yield remaining items directly — caller handles batching for IO
    yield from stream
